### ISSUE TITLE
ss 4.1 support

### ISSUE THREAD

**Issue by lekoala** [phptek/silverstripe-sentry#12]
Hello,

anything else I can do to help regarding the pull requests?

**Comment by phptek** [comment]
No, Sorry! Meant to sort these out on Tuesday. Tomorrow evening sir. (NZST)

**Comment by phptek** [comment]
Closing this now. I have a couple of 4.2 projects running with Sentry ^2.0 now and I consider it to be stable. I've also just tagged a 2.0 release.
