### ISSUE TITLE
Include GPS variables in reports

### ISSUE THREAD

**Issue by phptek** [phptek/silverstripe-sentry#16]
## User Story

As a Sentry user, I would like to see all the GET, POST and REQUEST variables available at the time a bug ocurred, so I can better debug what happened.

## Acceptance Criteria

* I can _always_ see GET, POST, REQUEST fields, regardless of their value (See #22 for context)
* When POST or GET requests are available, I can see a bullet list as a key => value
* When no such data is available, I can see "Unavailable"

**Comment by Firesphere** [comment]
I think Sentry already does this by default?
They turn up for me at least
