### ISSUE TITLE
a few things

### ISSUE THREAD

**Issue by lekoala** [phptek/silverstripe-sentry#2]
Hi,

I created two pull requests (https://github.com/phptek/silverstripe-sentry/pull/1 and https://github.com/phptek/silverstripe-sentry/pull/3) with the following changes:

- Collect user data before sending the message (because session is not available if initialized into _config.php)
- Use context provided by the message so that exceptions have a nice stack trace
- Properly filter the backtrace with the namespaced function

**Comment by phptek** [comment]
Thanks for these. See comments for both PR's. Merged one and close the other. Release v1.1.0.
Thanks!
