### ISSUE TITLE
Update sentry/sdk to v2

### ISSUE THREAD

**Issue by leepowellcouk** [phptek/silverstripe-sentry#21]
v2 of sentry/sdk is now available.

**Comment by phptek** [comment]
Nice one. Thanks. I'm on holiday and nowhere near a laptop (conscious decision). Feel free to issue a PR. I can review and merge however :-)

**Comment by phptek** [comment]
@leepowellcouk 3.0.0-alpha1 is available for use/review which contains the v2 SDK. Many thanks.
