### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by Firesphere** [phptek/silverstripe-sentry#24]
Is PHP 7.3 really not supported or is it legacy that is forgotten to be updated?

**Comment by phptek** [comment]
See the 3.0 branch. Check that out (it isn't yet stable, hence it still being in a branch and not a stable release). That supports >= 7.0

**Comment by phptek** [comment]
@Firesphere tagged 3.0.0-alpha1 for you, which uses `>=7.0`

**Comment by Firesphere** [comment]
Cheers!
