### ISSUE TITLE
Update to sentry 2.x

### ISSUE THREAD

**Issue by lekoala** [phptek/silverstripe-sentry#27]
Hi,

I'm getting the following error:
The Monolog\\Handler\\RavenHandler class is deprecated. You should rather upgrade to the sentry/sentry 2.x and use Sentry\\Monolog\\Handler, see https://github.com/getsentry/sentry-php/blob/master/src/Monolog/Handler.php

Any plan on updating this? do you need help ?

**Comment by phptek** [comment]
Which release are you using?

**Comment by lekoala** [comment]
the 2.x branch but now that i look, i see you have a 3.0.0 alpha using the right version. is it in a workable state ?

**Comment by phptek** [comment]
It hasn't yet been tested on a live sentry system, hence the alpha. Other than merging in the work ref'd in #26 it should be good to go. Let me know if it works for you and I'll put a little work into stabilising it. Thanks :-)

**Comment by phptek** [comment]
@lekoala The upgrade work is included in the 3.0 branch and has been tested as working by mself and two others. I'm going to close this one now. If you have any further questions or issues to report, I'm happy to review them - just log 'em in the usual way. Thanks!
