### ISSUE TITLE
Feature request: ability to init sentry via envs

### ISSUE THREAD

**Issue by phyzical** [phptek/silverstripe-sentry#35]
Currently i use a botched setup to inst sentry envs
           `Config::inst()->set("PhpTek\Sentry\Adaptor\SentryClientAdaptor", "opts", array ("dsn" => "https://$sentryDSN@xxx.com.au/$projectID"));`

prefer the ability to have silverstripe-sentry check for envs in the current environment if possible for the system to rely on

**Comment by phyzical** [comment]
proposed 

```
  protected function getOpts(string $opt = '')
    {
        $dsn = Environment::getEnv('SENTRY_DSN');
        if ($dsn)
        {
            Config::inst()->set(SentryAdaptor::class, 'opts', ['dsn' => $dsn]);
        }
```

**Comment by phyzical** [comment]
Confirmed as working, will make a pr later today (if you dont beat me to it) @phptek

**Comment by phptek** [comment]
Implemented in `3.0.0-beta4` - have a quiz and let me know if you have any problems. Apart from failing tests (which I'll get to) I'm pretty happy this can be stabilized at `3.0.0`

**Comment by phyzical** [comment]
3.0.0-beta5 using SENTRY_DSN works well thanks!

**Comment by phptek** [comment]
FYI You can now use 3.0.1 :-)

**Comment by phyzical** [comment]
Perfecto 3.0.1 runs like a dream via envs thanks again!

**Comment by phptek** [comment]
No, thank you :-)
