### ISSUE TITLE
php 7 support

### ISSUE THREAD

**Issue by lekoala** [phptek/silverstripe-sentry#4]
Is there a good reason why php7 is not allowed ? it would be great to allow it since SilverStripe 3.6 now accepts php7 as well

**Comment by phptek** [comment]
Hi, no. No good reason. I'll look into it. Feel free to test on 7 with 3.6. If tests pass, issue a PR. Thanks!

**Comment by lekoala** [comment]
i tested with the new sdk (1.7.0) and I've seen no particular issue. if I manage to get some time, i'll send a pr

**Comment by lekoala** [comment]
https://github.com/phptek/silverstripe-sentry/pull/5

done

**Comment by phptek** [comment]
Merged ages ago. Closing.
