### ISSUE TITLE
SS3.7.x + PHP7

### ISSUE THREAD

**Issue by Firesphere** [phptek/silverstripe-sentry#47]
PHP7 is not supported for SilverStripe 3.7.x versions, despite the framework supporting php7.

This causes installation issues with composer, that should not be necessary

**Comment by phptek** [comment]
If by "SilverStripe" you don't mean "framework", what do you mean?

**Comment by Firesphere** [comment]
The SS3 version has a limit to PHP < 7. Despite SS3.7.x supporting PHP7

**Comment by shanholmes** [comment]
+1. I've just come across this issue. SS3.7.x supports PHP7.3 but the version of this module limits the PHP <7.

**Comment by phptek** [comment]
If someone chucks me a PR I'll merge it

**Comment by Firesphere** [comment]
https://twitter.com/Firesphere/status/1288310045625577475?s=20

**Comment by shanholmes** [comment]
I've created a PR @ https://github.com/phptek/silverstripe-sentry/pull/52
There doesn't seem to be a branch for the 1.X version for me to merge into, so I have put it as master (sorry if thats wrong).
Maybe we could add a persistent 1.X branch rather than a tag?
Thanks!

**Comment by phptek** [comment]
Released `2.2.0` and `3.0.5` with relevant patches. Thanks folks.
