### ISSUE TITLE
Version 2.x not compatible with SS3

### ISSUE THREAD

**Issue by Firesphere** [phptek/silverstripe-sentry#56]
Despite what the docs say, 2.x has the requirement of `silverstripe\framework: ^4.0`

**Comment by Firesphere** [comment]
Duplicate, I did a booboo.

**Comment by Firesphere** [comment]
Not a duplicate. I did a booboo twice

**Comment by phptek** [comment]
> Despite what the docs say, 2.x has the requirement of `silverstripe\framework: ^4.0`

What do the docs say and where exactly?

All I see is that:

> Versions 2.x and 3.x should work with the same setups, the latter simply uses a newer version of the Sentry PHP SDK, and has a leaner codebase.

"The same setups" == "Silverstripe 4"

Are you saying that you'd like version 2.x of the lib to work with v3.x of Silverstripe framework? If so, that's a different issue (and one I can probably work with)

**Comment by Firesphere** [comment]
Ahhh, I misunderstood that.

Anyway, I have a SS3 set-up, that when adding the module, version two is auto-selected by Composer for some reason, which is strange.
