### ISSUE TITLE
Version 3.0.5 PHP7.4+ install issue

### ISSUE THREAD

**Issue by cameronbourgeois** [phptek/silverstripe-sentry#60]
The [Requirements section](https://github.com/phptek/silverstripe-sentry/blob/3.0.5/README.md#requirements) of the README gives us:

> SilverStripe 4
>   PHP >=7.0
>   SilverStripe ^4.0

> SilverStripe 3
>   PHP 5.4+, <=7.4
>   SilverStripe v3.1.0+, < 4.0

However, version 3.0.5 of this module seems to have [implemented a blanket requirement](https://github.com/phptek/silverstripe-sentry/commit/56b257a3dbbdc34b434d423695fafcafc5868d14) for `PHP 5.4+, <=7.4`, thereby making the module uninstallable on PHP 7.4+.

I need to downgrade back to 3.0.4 to get this module installed for my PHP7.4 / SS4 project.

**Comment by arthur-apanovics** [comment]
Having the same problem. Seems that SS3 requirement was accidentally used in [composer.json](https://github.com/phptek/silverstripe-sentry/blob/56b257a3dbbdc34b434d423695fafcafc5868d14/composer.json#L25).

**Comment by phptek** [comment]
Hi folks, so sorry about delays. I've had a few hours to dedicate to this. Can you try `3.0.10` which stipulates:

```
    "require": {
        "php": "^5.4|<7.5",
        "sentry/sdk": "^2",
        "silverstripe/framework": "^4"
    },
```

Perhaps it should just be:

```
    "require": {
        "php": ">=5.4",
        "sentry/sdk": "^2",
        "silverstripe/framework": "^4"
    },
```

@arthur-apanovics, @cameronbourgeois

**Comment by phptek** [comment]
Closing in light of the production of `3.0.10` and the imminent `4.0.0`
