### ISSUE TITLE
Sentry does not send exception to issues monitor 

### ISSUE THREAD

**Issue by cey0030** [phptek/silverstripe-sentry#61]
Hi, I am having an issue installing Sentry on SilverStripe 3. The exception is firing but Sentry isn't picking it up...spent more than a day trying to troubleshoot so far. I am using SilverStripe 3.6.7, PHP7.0.33 (must not change), phptek/sentry 1.1.2, and Composer version 1.10.13. The exception is happening on my local correctly but not appearing on the issues monitor.

**Comment by phptek** [comment]
Try a newer version of the library. 1.x is ancient. Try 2.2.0 and then 3.0.5

**Comment by cey0030** [comment]
Composer update yields this error when I swapped to Sentry version 2.2.0 
`Problem 1
    - silverstripe/framework 4.x-dev requires php ^7.1 || ^8 -> your PHP version (7.0.33) does not satisfy that requirement.
    - silverstripe/framework 4.7.x-dev requires php ^7.1 || ^8 -> your PHP version (7.0.33) does not satisfy that requirement.
    - silverstripe/framework 4.6.x-dev requires php >=7.1.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - silverstripe/framework 4.5.x-dev requires php >=7.1.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - Installation request for phptek/sentry 2.2.0 -> satisfiable by phptek/sentry[2.2.0].
    - Conclusion: remove silverstripe/framework 3.6.7
    - phptek/sentry 2.2.0 requires silverstripe/framework ^4 -> satisfiable by silverstripe/framework[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, 4.5.x-dev, 4.6.x-dev, 4.7.x-dev, 4.x-dev].  
    - Can only install one of: silverstripe/framework[4.2.x-dev, 3.6.7].
    - Can only install one of: silverstripe/framework[4.3.x-dev, 3.6.7].
    - Can only install one of: silverstripe/framework[4.4.x-dev, 3.6.7].
    - Installation request for silverstripe/framework 3.6.7 -> satisfiable by silverstripe/framework[3.6.7].`

**Comment by phptek** [comment]
OK - go back to 1.1.2 as that's (currently) the only supported version of the lib for Silverstripe 3.

Can you please copy/paste the following:

* An obfuscated example of your Sentry DSN config (abd where it is found: e.g. _config.php or some YML file)
* A description of how you the error should be reported to Sentry. i.e. is iit a type of `Exception` (automatic) or is it just a message pushed through to Sentry using `SS_Log::add_writer()` (manual)

Cheers.

**Comment by cey0030** [comment]
mysite/_config/sentry.yml

```---
Name: mysite-config-sentry
After:
  - 'sentry-config'
---


---
Only:
  environment: live
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    # Example DSN only. Obviously you'll need to setup your own Sentry "Project"
    dsn: https://xxx@xxx.ingest.sentry.io/xxxxxxx
---
Only:
  environment: test
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    # Example DSN only. Obviously you'll need to setup your own Sentry "Project"
    dsn: https://xxx@xxx.ingest.sentry.io/xxxxxxx
---
Only:
  environment: dev
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    dsn: null```

The exception I'm trying to trigger is "automatic" (thrown from Page.php init method):
// Test Sentry is working
throw new Exception("My first Sentry error!");

**Comment by phptek** [comment]
OK, In your first message you said that "The exception is happening on my local correctly" - so does that mean you're running in a Silverstripe "dev" environment, where you have `SS_ENVIRONMENT_TYPE="dev"` in `_ss_environment.php`? If so, the reason you're not seeing anything reported is because in your YML config, you have `null` set for the DSN.

Add the correct DSN to the "dev" condition, and it should work:

```
...
...
---
Only:
  environment: dev
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    dsn: https://xxx@xxx.ingest.sentry.io/xxxxxxx
...
...
```

**Comment by cey0030** [comment]
Yep, I have SS_ENVIRONMENT_TYPE set to "dev" in the environment file. I changed to the correct DSN, but the Sentry monitor is still not receiving the error:
mysite/_config/sentry.yml

Name: mysite-config-sentry
After:
  - 'sentry-config'
---


---
Only:
  environment: live
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    # Example DSN only. Obviously you'll need to setup your own Sentry "Project"
    dsn: https://xxx@xxx.ingest.sentry.io/xxxxxxx
---
Only:
  environment: test
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    # Example DSN only. Obviously you'll need to setup your own Sentry "Project"
    dsn: https://xxx@xxx.ingest.sentry.io/xxxxxxx
---
Only:
  environment: dev
---
PhpTek\Sentry\Adaptor\SentryAdaptor:
  opts:
    dsn: https://xxx@xxx.ingest.sentry.io/xxxxxxx

**Comment by phptek** [comment]
Did you flush Silverstripe's cache after you made the YML change? If not, Silverstripe will still think you have the old/stale config.

Where are you getting the "ingest.sentry.io" string from? I use sentry.io and the DSN's just end with "sentry.io" and a forward-slash and a numeric value after the slash, similar to the examples in the project README.

This really feels like an issue with your setup rather than the module as I haven't seen any reports of not being able to receive errors in 1.x (which has been around for a long time).

I'm  happy to continue helping, but double check the basics first, and ensure the DSN you're using is correct. Note that in Sentry's config there are at least _two_ different config identifiers, one is suitable for javascript setups and one for back-end setups. You'll need the latter.

**Comment by cey0030** [comment]
Yes, I already:
- Flushed the cache after the YAML change
- Checked that the DSN string is correct (copy pasted a few times from the sentry.io website, located at https://sentry.io/<organization>/<projectname>/getting-started/php/)

**Comment by Firesphere** [comment]
What's in your `mysite/_config.php`?

**Comment by Firesphere** [comment]
I might need to clarify this!

I found I need this in my `_config.php` of my project:
`SS_Log::add_writer(SentryLogWriter::factory(), SS_Log::ERR, '<=');`

**Comment by phptek** [comment]
@Firesphere `SentryLogWriter` has been removed since 2.x

**Comment by phptek** [comment]
@cey0030 FYI, I have patched a few things for v2 which should only be used for Silverstripe v3. Try 2.2.1

**Comment by phptek** [comment]
Update: v2.2.x is compatible with Silverstripe 3.7.x but I have seen some instances where data is not being sent. I'm going to take another look at this.

**Comment by phptek** [comment]
I'm an idiot. Because of #67 I have confused even myself. Ignore practically everything else I have said:

* 2.x & 3.x are for use with Silverstripe Framework v4
* 1.x is only for use with Silverstripe Framework v3

As such, this is a legitimate bug for Silverstripe 3 and package version 1.x and am investigating it now.

**Comment by phptek** [comment]
@cey0030 OK, so I just got this working (but admittedly in a 3.77 project), please try the following:

I set you wrong with the YML config above - that was for SS4. You'll need to do the following for SS3 along with what @Firesphere said previously:

1). YML Config:

```
phptek\Sentry\Adaptor\SentryClientAdaptor:
  opts: 
    dsn: YOUR_DNS
```
2). mysite/_config.php

```
SS_Log::add_writer(\phptek\Sentry\SentryLogWriter::factory(), SS_Log::ERR, '<=');
```

See the usage docs for further config and ways to adjust the severity of errors that will be reported, in the line of code above.

In the meantime, I have updated the README in `master`, `3.x`, 2.x` and `1.x` as it wasn't clear just by looking at them, what else was needed for Silverstripe 3.

I have also created release `1.2.3` which:

1. Removes the need to extend from Silverstripe 3's `Object` or `SS_Object` meaning the same package version will work in all SS v3 versions (Just tested in 3.7.7 and it was A-OK)
2. Relaxes the PHP version to use to anything >5.4

Please review the config and usage above, and try again with `1.2.3`.

Also - I have relx

For now, I will close this issue. If you still have problems, just open a new one and let me know what your setup is (if different from the one above).
