### ISSUE TITLE
Request to add tag for newest commit

### ISSUE THREAD

**Issue by cey0030** [phptek/silverstripe-sentry#62]
Hi,

I'd like to request a new tag be created for the current version of silverstripe-sentry as there was a bug which was fixed since the last tag similar to https://discourse.getgrav.org/t/the-reserved-indicator-cannot-start-a-plain-scalar-you-need-to-quote-the-scalar-at-line-1-near-extends/9947 (their solution did not work for me so I had to refer to the actual commit hash to get the latest version). 

I'm requesting this since my composer.json file ideally would not have a commit hash, and I'd much rather it had a version number instead. 

Thanks.

**Comment by phptek** [comment]
No problem. I should have really created one at the time. Give me 25m.

**Comment by phptek** [comment]
Assuming you wanted a release off master. Try 3.0.6.
