### ISSUE TITLE
Trailing comma in parameter list breaks backwards compatibility

### ISSUE THREAD

**Issue by andreaspiening** [phptek/silverstripe-sentry#75]
Hi mate,

the trailing comma in the Frame instantiation at the bottom of src/Log/SentryLogger.php:366 breaks compatibility with PHP versions before 7.3. You could bump up the minimum required PHP version from 7.0 to 7.3 in your version 4 or remove the trailing comma.

Cheers
Andy

**Comment by dcentrica** [comment]
Fixed in 4.0.4 :+1:
