### ISSUE TITLE
Incorrect Module Version

### ISSUE THREAD

**Issue by phptek** [phptek/silverstripe-sentry#81]
See below screenshot where incorrect module version is reported within the Sentry UI itself.

<img width="335" alt="Screen Shot 2022-03-29 at 08 30 06" src="https://user-images.githubusercontent.com/478440/160472651-c0695585-b261-4734-9585-892d0a3739d3.png">

**Comment by jonom** [comment]
Interesting. FWIW, this is what I get for this composer config

![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/477ec99e-711c-4600-9e9c-5299866069da)

![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/b8de1d17-2d6e-4ef8-8700-a304ad0eff08)

**Comment by phptek** [comment]
Confirmed in my local too. Could have been an issue with the Composer Installed Versions package. Closing.
