### ISSUE TITLE
User info is not recognised as user info

### ISSUE THREAD

**Issue by jonom** [phptek/silverstripe-sentry#85]
This might just be me, but for some reason Sentry isn't connecting the dots on the user information. It's visible as context info, but not as a user tag, which means I can't (easily) see if an issue is affecting multiple users. I couldn't see anything obvious in the module code about why this might happen. There's even a fancy question mark on the user context info 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/1079425/236880263-6580fb99-9a14-4f5c-b079-c3bfbaf1e11d.png)
![Screen Shot 2023-05-08 at 9 32 41 AM](https://user-images.githubusercontent.com/1079425/236880320-e9a5c201-919a-4255-869c-fa5d7e9ec87b.png)

**Comment by phptek** [comment]
I'd have to do some digging, but it doesn't look like Member data is being sent as a tag in `Log/SentryLogger::factory()`. Also, (and this may surprise you) I've never known what that question-mark means, especially when all the data is sent and available in the "User" section.

Have you tried hacking the module to the `defaultTags()` method? This is where all the tags are collected and pushed to Sentry. If that works, maybe I'll mod the module. I don't _think_ there was a reason user data _wasn't
_ made a tag, other than that there was already a specific place to set user data _alongside_ tagged data as a Sentry context.

**Comment by jonom** [comment]
Looks like the issue is [here](https://github.com/phptek/silverstripe-sentry/blob/05c1440ac65b6ba730fc9a742ef481e7418b1bce/src/Adaptor/SentryAdaptor.php#L123) - the array keys of the user data are incompatible with Sentry\UserDataBag so are added as metadata only when [parsed here](https://github.com/getsentry/sentry-php/blob/master/src/UserDataBag.php#L88).

![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/4f837eca-6525-4461-b4a0-fc31201f7d36)

**Comment by jonom** [comment]
Bingo! I'll open a PR.

![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/e6fa4f5c-96ba-4e60-8d25-ddfd1dae66d8)
