### ISSUE TITLE
user_error("...", E_USER_WARNING) sending a ErrorException to Sentry

### ISSUE THREAD

**Issue by KallivdH** [phptek/silverstripe-sentry#88]
This is more of a question than a problem in the code. Is it correct that user_error() also sends an ErrorException to Sentry at the error levels warning and notice?

**Comment by phptek** [comment]
AFAICT it depends on a). your application's code and b). your PHP environment. I think if you have `error_reporting(E_ALL)` set somewhere in php.ini or at the scdript level, then the Sentry server will receive `trigger_error()`, `user_error()` messages.

Have a look at the Sentry SDK for PHP which phptek/sentry is built on e.g.

https://github.com/getsentry/sentry-php/blob/b9856563f0c5b38273eea6f31995f928451eb870/tests/FunctionsTest.php#L170

**Comment by KallivdH** [comment]
Checked both the code and env for E_ALL and nothing found, unfortunately.

**Comment by KallivdH** [comment]
I looked on the production server and saw that error_reporting was giving 22519 back. So, that will be: error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);
